name:                type-errors
version:             0.2.0.2
github:              "isovector/type-errors"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Tools for writing better type errors
category:            Type

description:         Please see the README on GitHub at <https://github.com/isovector/type-errors#readme>

tested-with:
- GHC == 9.6.1
- GHC == 9.4.4
- GHC == 9.2.7
- GHC == 9.0.2
- GHC == 8.10.7
- GHC == 8.8.4
- GHC == 8.6.5
- GHC == 8.4.4
- GHC == 8.2.2
- GHC == 8.0.2

dependencies:
- base >= 4.9 && < 5
- first-class-families >= 0.5.0.0
- template-haskell
- th-abstraction
- syb

library:
  source-dirs: src

ghc-options:
  - -Wall

default-extensions:
  - ConstraintKinds
  - DataKinds
  - FlexibleContexts
  - LambdaCase
  - PolyKinds
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances

when:
  - condition: impl(ghc < 8.6)
    default-extensions:
      - TypeInType
  - condition: impl(ghc >= 9.2)
    default-extensions:
      - StandaloneKindSignatures

tests:
  test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - type-errors
    - doctest >= 0.16.0.1 && < 0.22

